package io.github.arkobat.softwarebot.casino;

enum ScramblePack {
    Youtube("Medie"),
    Facebook("Medie"),
    Twitter("Medie"),
    Discord("Medie"),
    TeamSpeak("Medie"),
    Snapchat("Medie"),
    Steam("Medie"),
    Twitch("Medie"),
    Spotify("Medie"),
    Audi("Bil mærker"),
    Citroen("Bil mærker"),
    Fiat("Bil mærker"),
    Ford("Bil mærker"),
    Honda("Bil mærker"),
    Nissan("Bil mærker"),
    Opel("Bil mærker"),
    Peugeot("Bil mærker"),
    Renault("Bil mærker"),
    Seat("Bil mærker"),
    Skoda("Bil mærker"),
    Suzuki("Bil mærker"),
    Toyota("Bil mærker"),
    Volvo("Bil mærker"),

    Fodbold("Sport"),
    Tennis("Sport"),
    Badminton("Sport"),
    Basketball("Sport"),
    Rundbold("Sport"),
    Baseball("Sport"),
    Golf("Sport"),
    Minigolf("Sport"),
    Karate("Sport"),
    Hockey("Sport"),
    Ishockey("Sport"),
    Motorcross("Sport"),
    Volleyball("Sport"),

    Word("Microsoft"),
    Office("Microsoft"),
    Excel("Microsoft"),
    Powerpoint("Microsoft"),
    Onedrive("Microsoft"),
    Onenote("Microsoft"),

    Belgien("Lande"),
    Danmark("Lande"),
    Finland("Lande"),
    Frankrig("Lande"),
    England("Lande"),
    Amerika("Lande"),
    Australien("Lande"),
    Kina("Lande"),
    Japan("Lande"),
    Korea("Lande"),
    Egypten("Lande"),
    Brasilien("Lande"),
    Holland("Lande"),
    Irland("Lande"),
    Rusland("Lande"),
    Island("Lande"),
    Italien("Lande"),
    Norge("Lande"),
    Polen("Lande"),
    Portugal("Lande"),
    Sverige("Lande"),
    Tyrkiet("Lande"),
    Tyskland("Lande"),

    Aarhus("Byer"),
    Odense("Byer"),
    Esbjerg("Byer"),
    Randers("Byer"),
    Kolding("Byer"),
    Skanderborg("Byer"),
    Roskilde("Byer"),
    Vejle("Byer"),
    Billund("Byer"),
    Skagen("Byer"),

    Antman("Marvel / DC"),
    Ironman("Marvel / DC"),
    Spiderman("Marvel / DC"),
    Wolverine("Marvel / DC"),
    Deadpool("Marvel / DC"),
    Avengers("Marvel / DC"),
    Thanos("Marvel / DC"),
    Batman("Marvel / DC"),
    Superman("Marvel / DC"),
    Aquaman("Marvel / DC"),
    Hulk("Marvel / DC"),
    Catwoman("Marvel / DC"),

    AndersAnd("Disney / Cartoon"),
    Andersine("Disney / Cartoon"),
    Fedtmule("Disney / Cartoon"),
    Mickey("Disney / Cartoon"),
    Pluto("Disney / Cartoon"),
    Sorteper("Disney / Cartoon"),
    Simba("Disney / Cartoon"),
    Moana("Disney / Cartoon"),
    Bambi("Disney / Cartoon"),
    Dumbo("Disney / Cartoon"),
    Snehvide("Disney / Cartoon"),
    Pinocchio("Disney / Cartoon"),
    Robinhood("Disney / Cartoon"),
    Peterplys("Disney / Cartoon"),
    Askepot("Disney / Cartoon"),
    Tornerose("Disney / Cartoon"),
    Junglebogen("Disney / Cartoon"),
    Peterpan("Disney / Cartoon"),
    Aladdin("Disney / Cartoon"),
    Pocahontas("Disney / Cartoon"),
    Herkules("Disney / Cartoon"),
    Mulan("Disney / Cartoon"),
    Tarzan("Disney / Cartoon"),
    Bolt("Disney / Cartoon"),
    Frozen("Disney / Cartoon"),
    Scoobydoo("Disney / Cartoon");

    String category;
    ScramblePack(String s) {
        category = s;
    }

    public String getCategory() {
        return category;
    }
}
